spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_NETWORK_HOST:localhost}:${POSTGRES_CONTAINER_PORT:5544}/supplier_db
    username: ${POSTGRES_USER:retailmanager}
    password: ${POSTGRES_PASSWORD:RetailMgr2024!}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.retailmanager: DEBUG
    org.hibernate.SQL: DEBUG
