# =========================================
# APP SETTINGS
# =========================================
spring.application.name=exchange-sv
server.port=8080
spring.profiles.active=${SPRING_ACTIVE_PROFILE:dev}
# =========================================
# LOGGING
# =========================================
logging.level.org.springframework=info
logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace
# =========================================
# ACTUATOR / MONITORING
# =========================================
# Custom base path because nginx routes by service name
#management.endpoints.web.base-path=/exchange/actuator
# Exposed endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus
# Health details always visible (may restrict later)
management.endpoint.health.show-details=always
# Enable exposing env info inside /info
management.info.env.enabled=true
# =========================================
# APPLICATION INFO (shown in /actuator/info)
# =========================================
info.app.name=Exchange Rate Service
info.app.description=Manages currency exchange rates
info.app.version=1.0.0
# =========================================
# SPRINGDOC / OPENAPI SWAGGER
# =========================================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true