spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_NETWORK_HOST:localhost}:${POSTGRES_CONTAINER_PORT:5544}/tenant_db
    username: ${POSTGRES_USER:retailmanager}
    password: ${POSTGRES_PASSWORD:RetailMgr2024!}

  rabbitmq:
    host: ${RABBITMQ_NETWORK_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.retailmanager: DEBUG
    org.hibernate.SQL: DEBUG
