spring:
  datasource:
    url: jdbc:postgresql://localhost:5544/tenant_db
    username: retailmanager
    password: RetailMgr2024!

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.retailmanager: DEBUG
    org.hibernate.SQL: DEBUG
