spring:
  application:
    name: gateway-sv
  jmx:
    enabled: false

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.cloud.gateway: DEBUG
    sun.rmi: WARN
    javax.management.remote.rmi: WARN

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env
