spring:
  application:
    name: gateway-sv

logging:
  level:
    root: WARN
    org.springframework: INFO
    org.springframework.web: WARN
    org.springframework.cloud.gateway: WARN

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
