spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_NETWORK_HOST}:${POSTGRES_CONTAINER_PORT}/identity_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: WARN
    org.springframework: WARN
    com.retailmanager: INFO

management:
  endpoint:
    health:
      show-details: when_authorized
